version: '2.1'
services:
  influxdb:
    image: influxdb:1.1
    ports:
      - "8083:8083"
      - "8086:8086"
    expose:
      - "8086"
  grafana:
    image: grafana/grafana:4.0.1
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
  cicada:
    build: .
    depends_on:
      - influxdb
    ports:
      - "4000:4000"
